[package]
name = "ssg"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-cmark = "^0.12.2"
latex2mathml = "0.2.3"
ramhorns = "1.0.1"

# for web server
warp = "0.3"
notify = "5.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
