[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.82.1"
  HUGO_BASEURL = "https://make-a-hugo-blog-from-scratch.netlify.app"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
