[package]
name = "site"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-cmark = "^0.13"
latex2mathml = "0.2.3"
ramhorns = "1.0.1"
serde_yaml="0.9"
tidier = "0.5.3"

warp = "0.3"
tokio = { version = "1", features = ["full"] }
